### ISSUE TITLE
Write up user stories

### ISSUE THREAD

**Issue by mdchia** [spsaswat/APPF_FLIR#11]
There needs to be a User Stories document in the Sharepoint. 

One way of doing it is via an excel template such as https://www.aha.io/roadmapping/guide/requirements-management/what-is-a-good-feature-or-user-story-template
(I'd suggest something like the Thematic template and then you can group it by shareholder type or constraints vs. needs etc.)

You can also make a Word doc and have a numbered list of user stories,

**Comment by Abel-github** [comment]
@Zehua2015 I am taking this issue.

**Comment by spsaswat** [comment]
Thanks for creating the user stories. I am closing this issue.
