### ISSUE TITLE
tune color map to make plants visible in the thermal image

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#13]
check various ran in color map using vmin and vmax. start with fin the minimum and maximum pixel (temp) value.

**Comment by Yash9988** [comment]
![image](https://github.com/spsaswat/APPF_FLIR/assets/31058288/4f334202-08f0-4355-b610-a22d3b7b221d)
![image](https://github.com/spsaswat/APPF_FLIR/assets/31058288/251e2f64-8302-492e-8cc9-70d4ccfab97e)

Image underflow, when applying cmap, has been fixed to the best of my ability. @spsaswat, please review at your convenience

**Comment by spsaswat** [comment]
Thanks @Yash9988
