### ISSUE TITLE
test capture code in realsense D405

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#14]
`pip install pyrealsense2`
https://pypi.org/project/pyrealsense2/

connect the camera to your laptop and test a frame capture, of rgb and depth

**Comment by spsaswat** [comment]
`pip install opencv-python`
https://pypi.org/project/opencv-python/

**Comment by spsaswat** [comment]
# Configure the RealSense camera
pipeline = rs.pipeline()
config = rs.config()
config.enable_device(serial_number)

# config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30) #L515
# config.enable_stream(rs.stream.depth, 1024, 768, rs.format.z16, 30)  #L515
# config.enable_stream(rs.stream.color, 1920, 1080, rs.format.bgr8, 30) #D435
# config.enable_stream(rs.stream.depth, 1280, 720, rs.format.z16, 30)  #D435
config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30) #D405
config.enable_stream(rs.stream.depth, 1280, 720, rs.format.z16, 30)  #D405

# Align depth frame to color frame
align = rs.align(rs.stream.color)




# Start pipeline and capture initial frames
start_pipeline()

# Save intrinsics
save_intrinsics()

for i in range(2):
    frames = pipeline.wait_for_frames()
    frames = pipeline.wait_for_frames()

capture_images(pipeline, current_position)

Can you use that below the function

**Comment by zzzshuang** [comment]
Hi Saswat@spsaswat , the task has been completed. Please close this issue.

**Comment by spsaswat** [comment]
Thanks @zzzshuang for finsihing this task.
