### ISSUE TITLE
document how to run SALT on ubuntu desktop GPU

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#17]
https://github.com/spsaswat/APPF_FLIR/blob/main/SALT_docs.md

Update the document above on how to run the helper scripts and also how to run annotator and label image.

**Comment by wanqiqiu** [comment]
we did the first version on this two weeks ago, we will keep up-to-date for this documentation

**Comment by spsaswat** [comment]
Thanks for the work. I am closing the issue now.
