### ISSUE TITLE
Calibrate D405 and Thermal camera

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#20]
https://github.com/spsaswat/APPF_FLIR/blob/main/SensorCommunication/Acquisition/calib_data.zip
1) use code to focus on these circles from both the camera (actual diameter 30mm), and make all other pixels black.:
![image](https://github.com/spsaswat/APPF_FLIR/assets/45821961/62b8df97-73d3-47f0-926f-f7f1bc93fd92)
![image](https://github.com/spsaswat/APPF_FLIR/assets/45821961/cf4ab7de-b18b-4c01-bc87-a86f7062a81a)
2) try calibrating by aligning images to the centre of the circles.

you don't need to calibrate the depth image.

**Comment by spsaswat** [comment]
please recalibrate and align so that we can have maximum common region between the two cameras

**Comment by zzzshuang** [comment]
Hi Saswat@spsaswat, i've updated the calibration code to allow detection of the blue bounding box on RGB images without cropping, and create a mask to cover irrelevant areas. Please take a moment to review it.

**Comment by mdchia** [comment]
Hardcoded paths (e.g. https://github.com/spsaswat/APPF_FLIR/blob/1d4643a8c13d0d65419fd623beff57c1aa4d76ae/camera_calibration.py#L159 ) should be refactored into a script argument or maybe folder config variable (if it expects a particular folder structure, that should be documented)

**Comment by zzzshuang** [comment]
Hi, i reconstructed the calibration code, kindly review it please.
