### ISSUE TITLE
Test for response from gantry api

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#22]
import requests

requests.get("http://localhost:8010/RestPLCService/setint?address=4010&value=1300")
print(requests.get("http://localhost:8010/RestPLCService/getint?address=4020").json()["Value"])

**Comment by spsaswat** [comment]
def readCameraPos():
    return int(requests.get("http://localhost:8010/RestPLCService/getint?address=4020").json()["Value"])


def moveCamera(position):
    requests.get("http://localhost:8010/RestPLCService/setint?address=4010&value=%d" % position)


Use the above fucntions to communicate with the gantry

**Comment by ConnorLirongxu** [comment]
> import requests
> 
> requests.get("http://localhost:8010/RestPLCService/setint?address=4010&value=1300") print(requests.get("[http://localhost:8010/RestPLCService/getint?address=4020").json()["Value"]](http://localhost:8010/RestPLCService/getint?address=4020%22).json()%5B%22Value%22%5D))

![image](https://github.com/spsaswat/APPF_FLIR/assets/139671083/ef8c40c7-92ce-4d80-a60b-b5dfa129d8a4)

**Comment by ConnorLirongxu** [comment]
gantry communication successful
