### ISSUE TITLE
Capture image at relevant positions 

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#25]
https://github.com/spsaswat/APPF_FLIR/blob/main/SensorCommunication/gantry_communication_code.ipynb

just below the `# call rgbd and thermal capture`

Please use https://github.com/spsaswat/APPF_FLIR/blob/main/SensorCommunication/relasense_capture.py (capture one rgb and one depth image)
and https://github.com/spsaswat/APPF_FLIR/blob/main/SensorCommunication/capture_thermal_image.py (capture one thermal)

**Comment by spsaswat** [comment]
in the capture_thermal_image.py NUM_IMAGES =   20 # number of images to grab
make it 1

similarly in realsense
capture_images(pipeline, total_images=10, delay=1)
make delay 0 and total images 1

**Comment by ConnorLirongxu** [comment]
Hi @spsaswat could you please review the code?

**Comment by spsaswat** [comment]
Thanks the code is working.
