### ISSUE TITLE
Underflow error in thermal images

### ISSUE THREAD

**Issue by mdchia** [spsaswat/APPF_FLIR#26]
I've had a look at some of the images and plotting a value profile over the leaves leads me to strongly suspect an underflow error of some kind. (likely in converting the thermal data to 8-bit and/or saving as JPG) 

This doesn't have to be solved for calibration purposes, but would be good to document as a known bug for future work.

![Screenshot_20240501_162506](https://github.com/spsaswat/APPF_FLIR/assets/12966829/18ee9d13-cc34-48c5-a22b-7735e0d505ea)

**Comment by spsaswat** [comment]
![image](https://github.com/user-attachments/assets/c0d9d46b-915d-430e-806d-46632ab5f7ca)
Try using Mono16 (capture_thermal_image.py) and should be able to store mono16 in python image format
