### ISSUE TITLE
Calibration metrics

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#27]
@zzzshuang could you check for some calibration metrics like error?

**Comment by zzzshuang** [comment]
Hi @spsaswat , I have tested all the test files i got, the alignment error were 1.75 pixels, 1.68 pixels, 1.24 pixels, 1.28 pixels, 0.90 pixels, 0.83 pixels and 0.74 pixels. Kindly review it please.
<img width="1140" alt="issue27" src="https://github.com/spsaswat/APPF_FLIR/assets/135477161/ddc02f2a-0dd5-41a2-80be-9763959bc2c1">

**Comment by spsaswat** [comment]
Thanks @zzzshuang, I am closing the issue now.
