### ISSUE TITLE
Install and Setup Development Environment

### ISSUE THREAD

**Issue by wanqiqiu** [spsaswat/APPF_FLIR#28]
**### Activities:**

**1. Install Anaconda:**

Download and install Anaconda from https://www.anaconda.com/products/distribution.
Create a new environment for the project:

```
conda create -n thermal_calibration python=3.8
conda activate thermal_calibration
```

**2. Install calibration tools (e.g., OpenCV) and necessary Python libraries using conda:**

```
conda install opencv
```

**3. Setup Project Repository:**

**Ensure the environment is activated:**
`conda activate thermal_calibration
`

**Comment by ConnorLirongxu** [comment]
We setup the development environment successfully
