### ISSUE TITLE
Add details about the thermal camera and appf to Readme.md markdown file

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#3]
Add details about APPF.
Add details about the thermal camera.
Add link to the test docs.

**Comment by Zehua2015** [comment]
Hi @spsaswat, issue completed. Could you please review the readme when available?

**Comment by spsaswat** [comment]
![image](https://github.com/spsaswat/APPF_FLIR/assets/45821961/535a6094-34be-420f-8091-402a2e4f1569)
@Zehua2015 could you please try to condense the information about the camera (by little bit) and provide a reference link (for more information please visit the link.

**Comment by spsaswat** [comment]
![image](https://github.com/spsaswat/APPF_FLIR/assets/45821961/14cad2d3-a6d6-4b21-a372-50011b46ebfe)
@Abel-github please condense the list max 5 points (must include resolution, range, filter type and accuray/error). Provide a reference link for more information please visit [link].

**Comment by Abel-github** [comment]
@spsaswat I have modified the relevant information about Realsense D405.
