### ISSUE TITLE
Use colormap for visualizing raw thermal image

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/APPF_FLIR#9]
1. The colour map used for most thermal images is IRONBOW.
2. The closest to that colormap in Python matplotlib is Inferno.
3. Or use a custom color map
`ironbow_colors = [
    (0, 0, 0),        # Black
    (0.5, 0, 0.5),    # Dark purple
    (0, 0, 1),        # Blue
    (0, 1, 1),        # Cyan
    (0, 1, 0),        # Green
    (1, 1, 0),        # Yellow
    (1, 0.5, 0),      # Orange
    (1, 0, 0),        # Red
    (1, 1, 1)         # White
]`

`# Create the colormap`
`ironbow_cmap = LinearSegmentedColormap.from_list("custom_ironbow", ironbow_colors, N=256)`

**Comment by spsaswat** [comment]
https://github.com/spsaswat/APPF_FLIR/tree/main/SensorCommunication/Acquisition/20240310-132157

Solving this issue does not require installing spinnaker. read the images in the Acquisition/20240310-132157 folder and apply color-map and save them in the Acquisition/20240310-132157 folder with names like inferno_1, inferno_2 or 
c_ironbow_1, c_ironbow_2...

**Comment by Yash9988** [comment]
All tasks have been accomplished. Kindly review and close the issue @spsaswat

**Comment by spsaswat** [comment]
@zzzshuang and @Yash9988 thank you for your work. The code looks great. I have one suggestion for now.
Can the number of images be identified automatically; for i in range(20)? You may look for file names ending with pattern = r'on-\d+\.jpg$'. Thank you.

**Comment by zzzshuang** [comment]
Hi, I've added the "automatically identify and enumerate images in a directory " function to the code, and the code now can let users choose  between 'inferno' and 'custom' colormaps to use. Please take a look and let me know if there is any questions. @spsaswat

**Comment by spsaswat** [comment]
Thanks @zzzshuang and @Yash9988, I am closing this issue for now. I will open another issue for colormap tuning to make the plant visible.
